### PR TITLE
Update bg.psv

### PR DESCRIPTION
**Pull request by Julleht**
Added Trend and fixed some older polls

### CODE REVIEW

**Comment by roshavagarga** [comment]
@Julleht Where did you get those Trend numbers from?
That poll is available [here](https://rctrend.bg/project/%D0%BD%D0%B0%D0%B3%D0%BB%D0%B0%D1%81%D0%B8-%D0%BD%D0%B0-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D0%B8%D1%82%D0%B5-%D1%81%D0%BF%D1%80%D1%8F%D0%BC%D0%BE-%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%B8%D1%82-5/) and as you can clearly see (check in with your Bulgarian political analyst if you'd like), it lists 100% of the voter-only results, hence there's nothing to recalculate and the results can just be copied over. This has been the case for Trend polls for a long time...

On top of that, I'm against data I corrected being resubmitted by you at a later date as a new pull request under your name/account - I put in the work a week earlier and I'd like to get the credit I deserve in the commit history. You can, per the typical git etiquette, add to my pull request and wait for that to get fixed or message me in that PR and ask for changes, if you don't have the status in this repository to add commits to PRs.

**Comment by Julleht** [comment]
Apologies, I did not even think I am stepping on someone's toes with this. My intention is just to fill out our database accurately so I can run our average code, I do not care about git credit, I am happy if you can somehow backedit that part. I merely matched the polls with [what we have published](https://twitter.com/search?q=from%3Aeuropeelects%20bulgaria&src=recent_search_click). We routinely exclude don't know's and refusals (не подкрепям никого), which, without checking now again, I assume the difference is from.

That said, seems that I didn't exclude them in [latest trend](https://rctrend.bg/project/%d0%bd%d0%b0%d0%b3%d0%bb%d0%b0%d1%81%d0%b8-%d0%bd%d0%b0-%d0%b1%d1%8a%d0%bb%d0%b3%d0%b0%d1%80%d0%b8%d0%b5-%d1%81%d0%bf%d1%80%d1%8f%d0%bc%d0%be-%d0%be%d1%81%d0%bd%d0%be%d0%b2%d0%bd%d0%b8%d1%82%d0%b5/). Regardless, that would be the intention, because one cannot vote 'I refuse to vote' party in the voting booth.

Best,

**Comment by Julleht** [comment]
Checking now, I did not even notice you had made a pull request for the trend poll earlier too. Sorry for doubling up, should see the pull requests before committing. I am not accustomed to someone else being so fast with this :)

**Comment by roshavagarga** [comment]
I was talking about the the October Trend poll you changed, not just adding the last one tbh.

To make it clear, I'm the person that's doing the recalculations for the Wikipedia articles [here](https://en.wikipedia.org/wiki/2021_Bulgarian_parliamentary_election) and [here](https://bg.wikipedia.org/wiki/%D0%9F%D0%B0%D1%80%D0%BB%D0%B0%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%BD%D0%B8_%D0%B8%D0%B7%D0%B1%D0%BE%D1%80%D0%B8_%D0%B2_%D0%91%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D0%B8%D1%8F_(2021)). Data has been taken by you or someone else from those in the past - I know because I rounded up and fixed my own calculations with PRs here a few times, since the Bulgarian Wikipedia staff advised me to round up to .1s, instead of .01s and I'd made a few wrong calculations here and there over time.

I'm confused, has your political analyst not told you? The option "Не подкрепям никого" can be best translated as "None of the above" and is available as an option on the ballot, has been for a number of years in fact. It does affect the voting process - people who might not have voted at all as a form of protest might choose "None of the above" to do the same, thus raising the difficulty for parties to reach the 4% parliament threshold, due to a higher voter turnout. I also exclude don't know's and refusals, but the refusals are worded as "Няма да гласувам" (I will not vote). I will note that not all pollsters give both options.

**Comment by Julleht** [comment]
At some point during last autumn I manually checked all polls from the primary sources I could find, but we do have a scraping tool of sorts, which scrapes wikipedia polling tables for specific countries. I assume this was the case with Bulgaria too at some point. I did not in fact know about the option to vote 'no one' in voting booth, thank you for that and it definitely affects the dynamic. Perhaps the Bulgarian correspondents thought it a self-evident custom not woth mentioning, it has in any case not frequently been brought up.

In yesteryears the Bulgarian track record of us has been rather spotty and at times inactive, which has had multiple spillovers like this carrying up to today, where our coverage hadn't captured all the nuances of the country. The elections offer us a sort of 'fresh start', after which we can more freely change many things in polling posts without affecting the consistency. There is no retroactively fixing the old polls, but at least we can get the database and hence the average to accurately portray the party supports.

A lot of work to do. I will delete this pull once you've read the comment so as not to make double commits. I will surely ask your input in future, thanks.

**Comment by roshavagarga** [comment]
I will note that I'm a volunteer - I'm not a lawyer, I haven't studied political sciences or sociology.

Barring that - Bulgaria doesn't seem to have a legal standard for its opinion polls, or I've never found it. That's probably why most of the pollsters don't word their questionnaires in the same way, there's no central database of poll results, etc. That's one of the issues with recalculating data - one of the last 2 or 3 polls actually mentioned that they had "around 2% for none of the above" yet they didn't include that in their data at all, so even the recalculation will be slightly off.

The tables in those wikipedia articles have the links to the primary sources where available on the left, so they can be doublechecked.

Technically speaking, I have a faint memory of the election code (last updated this December) having something about 'none of the above' not being used to calculate Presidential election results when over 50% of the possible voters have voted, which makes it both valid and invalid in that case or something of the sort.

Something I brought up in a now-closed issue and I'd like to revisit - a Specter poll/polls was/were removed in an earlier pull request/merge. On one hand, I'd agree with this, since they don't have an official website or source, so their results can only be found from news articles. If I remember correctly, it was said that this was done after consulting with your volunteer political analyst. On the other hand, I disagree with this, since there's a worse case of the same - Barometer has 0 online presence and they spew out a lot more polls. On top of that, an article by Radio Free Europe Bulgaria stated that the company behind that pollster only has 1 person on the payroll, so theoretically they might not even be able to create polls. Other pollsters also chimed in, in said article, and claimed that the data was manipulated. You can check the Bulgarian wiki article, beneath the tables there's a graphical representation of the results. The first button includes Barometer polls and the second doesn't - you can clearly see there that their results heavily skew towards the United Patriots (Obedineni Patrioti), while none of the other polls give them that high of a percentage. So my question is, if you're getting rid of Specter, why not Barometer too?

I like averages, but maybe it would be nice if you also weighed your results based on how far off pollsters were like FiveThirtyEight?

Barring all of that, I'd be fine with giving my opinion and helping out with data as I've done so far, even searching for older data and recalculating it. Close this, but don't delete it, so I can check whether I actually missed something between this and mine.

**Comment by roshavagarga** [comment]
@Julleht Market Links polls are now posted and there's a slight issue: They've been posting two polls simultaneously for a while one, one that typically has around 500 voters data, and one with 1000 general pollees' data. These are always posted on the same day and have slight variations in the percentages, not so slight this time. So far, Europe Elects has used the general one's data a few times and the voters only one once. Shouldn't the data from all of these be added? I've recalculated both as always and you can see the differences in recalculated percentages [here](https://i.imgur.com/x3A8Bli.jpeg).
Translation of columns: Agency / Date / Pollees / Margin of error / GERB / BSP / DPS / OP / DB / Volya / ABV / V / Ataka / ITN / IS.BG / RzB / Other,none / Lead / Activity.
Activity in this case is the combined percentages of all votes for a party or none of the above, sometimes the poll agencies actually post an Activity percentage that's usually lower.

**Comment by Julleht** [comment]
Sorry for the delay.

Europe Elects has not published Barometer polls either, exactly because they are so dubious and show wildly different results than other pollsters. They have not been in our database either earlier, but apparently now they are. I would be happy to discuss this and keep our coverage rather intact in a way our country correspondents wish.

We posted Market Links yesterday with the 'all' category and excluded don't knows. You can see it [here](https://twitter.com/EuropeElects/status/1357064247205916675). I'm open to discussing whether to include both 'voters' and 'all'.

I will also now close this pull so it does not get merged. Happy to discuss with you elsewhere.

**Pull request closed without merging**
