### PR TITLE
EM Approval rating

### PR DESCRIPTION
**Pull request by andreimiclea99**
I have the approval of Tobias and Julius for this.

### CODE REVIEW

**Comment by Julleht** [comment]
As we now have the approval data from elsewhere, I think this could finally be closed for good.

**Comment by filipvanlaenen** [comment]
But do we have the data in a structured form somewhere? The problem with this pull request is that it doesn't follow the format of the other files.

**Comment by andreimiclea99** [comment]
This is almost one year old PR.

I took this data, back then, with one python line from wikipedia.

I forgot to change the file format and none said anything, anyway.

It would be a good to automate the process of gathering polls from wiki into this repo.

**Comment by Julleht** [comment]
I have the approval data of French President and French PM from the Executive Approval Project starting from 1960s and reaching up to February 2021. We receive an updated batch every few months and the chart is live in https://europeelects.eu/france/

For copyright reasons we probably cannot make it publicly available and in GitHub, but the data exists.

**Pull request closed without merging**
