### PR TITLE
Update de.psv

### PR DESCRIPTION
**Pull request by Julleht**
Added INSA poll

### CODE REVIEW

**Comment by filipvanlaenen** [comment]
INSA is actually INSA and YouGov.
Also, they usually publish results for CDU and CSU separately. Are they available yet?
I can see there's also a new Emnid poll for Germany.

**Comment by Julleht** [comment]
No breakdown yet, will edit this pull request for the split before it should be merged.

In general, should I do a separate pull request for each poll? How do they interact together if all are merged?

**Comment by filipvanlaenen** [comment]
OK.
Best to do a pull request per file, but it's OK to add multiple polls in the same file in the same pull request.

**Comment by Julleht** [comment]
Should be okay now, can't merge

**Pull request merged**
